
document.write('<style type="text/css">');
document.write('.cis_new_year_box_timer {height:159px; width:600px; background:url(' + addressSite + themesDir + currentTheme + '/images/newyear-background.jpg) no-repeat !important;');
document.write('background-image: none;');
document.write('filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=' + addressSite + themesDir + currentTheme + '/images/newyear-background.jpg,sizingMethod=crop);}');
document.write('.cis_new_year_box_timer_1 {margin:0; padding:0; position:relative;}');
document.write('#cis_new_year_heppi_timer {position:absolute; top:30px; left:225px; width:285px; height:35px; overflow:hidden;}');
document.write('.cis_new_year_timers_time {background:url(' + addressSite + themesDir + currentTheme + '/images/newyear-happy.png) top no-repeat;}');
document.write('.cis_new_year_timers_stop {background:url(' + addressSite + themesDir + currentTheme + '/images/newyear-happy.png) bottom no-repeat;}');
document.write('#cis_new_year_heppi_timer_1 {position:absolute; top:135px; left:206px; width:325px; height:21px; overflow:hidden;}');
document.write('.timer {background-image:url(' + addressSite + themesDir + currentTheme + '/images/newyear-numbers.gif); width:35px; height:60px; overflow:hidden;}');
document.write('#cis_new_year_d_1, #cis_new_year_d_2, #cis_new_year_h_1, #cis_new_year_h_2, #cis_new_year_m_1, #cis_new_year_m_2, #cis_new_year_s_1, #cis_new_year_s_2 {width:35px; height:60px; overflow:hidden; position:absolute; top:78px;}');
document.write('#cis_new_year_d_1 {left:210px;}');
document.write('#cis_new_year_d_2 {left:247px;}');
document.write('#cis_new_year_h_1 {left:292px;}');
document.write('#cis_new_year_h_2 {left:328px;}');
document.write('#cis_new_year_m_1 {left:373px;}');
document.write('#cis_new_year_m_2 {left:409px;}');
document.write('#cis_new_year_s_1 {left:454px;}');
document.write('#cis_new_year_s_2 {left:490px;}');
document.write('#ID_ANIMATE {position:relative; overflow:hidden; width:600px; height:159px;}');
document.write('#ID_ANIMATE IMG {position:absolute; width:24px; height:24px; font-size:0px; z-index:1;}');
document.write('</style>');
document.write('<table align="center" valign="middle">');
document.write('<tr><td style="cursor:pointer;cursor:hand;" onclick="location.href=\'#\';">');
document.write('<div id="ID_ANIMATE" style="z-index: 2;">');
document.write('<div class="cis_new_year_box_timer">');
document.write('<div class="cis_new_year_box_timer_1">');
document.write('<div id="cis_new_year_heppi_timer" class="cis_new_year_timers_time"></div>');
document.write('<div id="cis_new_year_d_1"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_d_2"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_h_1"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_h_2"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_m_1"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_m_2"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_s_1"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_s_2"><div class="timer"></div></div>');
document.write('<div id="cis_new_year_heppi_timer_1" class="cis_new_year_timers_time_1"></div>');
document.write('</div></div>');
document.write('<script type="text/javascript">');
document.write('var timer;');
document.write('var totalRemains;');
document.write('var totalTimer;');
document.write('var now = new Date();');
document.write('var newNewyear = new Date("Dec 31 2010 23:59:59");');
document.write('var totalT = (newNewyear.getTime()-now.getTime());');
document.write('if(navigator.userAgent.indexOf("MSIE 6") != -1) {');
document.write('totalTimer = totalT - 3600000;');
document.write('} else {');
document.write('totalTimer = totalT; }');
document.write('newNewyearIn(totalTimer);');
document.write('function newNewyearIn(timer) {');
document.write('if(!timer) timer = timTimer;');
document.write('totalRemains = timer - 1000;');
document.write('timTimer = totalRemains;');
document.write('if (totalRemains>1) {');
document.write('setTimeout("newNewyearIn()",1000);');
document.write('var RemainsSec=(parseInt(totalRemains/1000));');
document.write('var RemainsFullDays=(parseInt(RemainsSec/(24*60*60)));');
document.write('var secInLastDay=RemainsSec-RemainsFullDays*24*3600;');
document.write('var RemainsFullHours=(parseInt(secInLastDay/3600));');
document.write('if (RemainsFullHours<10){RemainsFullHours="0"+RemainsFullHours};');
document.write('var secInLastHour=secInLastDay-RemainsFullHours*3600;');
document.write('var RemainsMinutes=(parseInt(secInLastHour/60));');
document.write('if (RemainsMinutes<10){RemainsMinutes="0"+RemainsMinutes};');
document.write('var lastSec=secInLastHour-RemainsMinutes*60;');
document.write('if (lastSec<10){lastSec="0"+lastSec};');
document.write('var timer_s = lastSec;');
document.write('var timer_s_1;');
document.write('var timer_s_2;');
document.write('if(timer_s < 0) {');
document.write('timer_s_1 = 0;');
document.write('timer_s_2 = timer_s;');
document.write('} else {if(timer_s < 10) {');
document.write('timer_s_1 = 0;');
document.write('timer_s_2 = timer_s;');
document.write('} else {if(timer_s < 20) {');
document.write('timer_s_1 = 1;');
document.write('timer_s_2 = timer_s - 10;');
document.write('} else {if(timer_s < 30) {');
document.write('timer_s_1 = 2;');
document.write('timer_s_2 = timer_s - 20;');
document.write('} else {if(timer_s < 40) {');
document.write('timer_s_1 = 3;');
document.write('timer_s_2 = timer_s - 30;');
document.write('} else {if(timer_s < 50) {');
document.write('timer_s_1 = 4;');
document.write('timer_s_2 = timer_s - 40;');
document.write('} else {if(timer_s < 60) {');
document.write('timer_s_1 = 5;');
document.write('timer_s_2 = timer_s - 50; }}}}}}}');
document.write('var timer_m = RemainsMinutes;');
document.write('var timer_m_1;');
document.write('var timer_m_2;');
document.write('if(timer_m < 0) {');
document.write('timer_m_1 = 0;');
document.write('timer_m_2 = timer_m;');
document.write('} else {if(timer_m < 10) {');
document.write('timer_m_1 = 0;');
document.write('timer_m_2 = timer_m;');
document.write('} else {if(timer_m < 20) {');
document.write('timer_m_1 = 1;');
document.write('timer_m_2 = timer_m - 10;');
document.write('} else {if(timer_m < 30) {');
document.write('timer_m_1 = 2;');
document.write('timer_m_2 = timer_m - 20;');
document.write('} else {if(timer_m < 40) {');
document.write('timer_m_1 = 3;');
document.write('timer_m_2 = timer_m - 30;');
document.write('} else {if(timer_m < 50) {');
document.write('timer_m_1 = 4;');
document.write('timer_m_2 = timer_m - 40;');
document.write('} else {if(timer_m < 60) {');
document.write('timer_m_1 = 5;');
document.write('timer_m_2 = timer_m - 50; }}}}}}}');
document.write('var timer_h = RemainsFullHours;');
document.write('var timer_h_1;');
document.write('var timer_h_2;');
document.write('if(timer_h < 0) {');
document.write('timer_h_1 = 0;');
document.write('timer_h_2 = timer_h;');
document.write('} else {if(timer_h < 10) {');
document.write('timer_h_1 = 0;');
document.write('timer_h_2 = timer_h;');
document.write('} else {if(timer_h < 20) {');
document.write('timer_h_1 = 1;');
document.write('timer_h_2 = timer_h - 10;');
document.write('} else {if(timer_h < 30) {');
document.write('timer_h_1 = 2;');
document.write('timer_h_2 = timer_h - 20;');
document.write('} else {if(timer_h < 40) {');
document.write('timer_h_1 = 3;');
document.write('timer_h_2 = timer_h - 30;');
document.write('} else {if(timer_h < 50) {');
document.write('timer_h_1 = 4;');
document.write('timer_h_2 = timer_h - 40;');
document.write('} else {if(timer_h < 60) {');
document.write('timer_h_1 = 5;');
document.write('timer_h_2 = timer_h - 50; }}}}}}}');
document.write('var timer_d = RemainsFullDays;');
document.write('var timer_d_1;');
document.write('var timer_d_2;');
document.write('if(timer_d < 0) {');
document.write('timer_d_1 = 0;');
document.write('timer_d_2 = timer_d;');
document.write('} else {if(timer_d < 10) {');
document.write('timer_d_1 = 0;');
document.write('timer_d_2 = timer_d;');
document.write('} else {if(timer_d < 20) {');
document.write('timer_d_1 = 1;');
document.write('timer_d_2 = timer_d - 10;');
document.write('} else {if(timer_d < 30) {');
document.write('timer_d_1 = 2;');
document.write('timer_d_2 = timer_d - 20;');
document.write('} else {if(timer_d < 40) {');
document.write('timer_d_1 = 3;');
document.write('timer_d_2 = timer_d - 30;');
document.write('} else {if(timer_d < 50) {');
document.write('timer_d_1 = 4;');
document.write('timer_d_2 = timer_d - 40;');
document.write('} else {if(timer_d < 60) {');
document.write('timer_d_1 = 5;');
document.write('timer_d_2 = timer_d - 50; }}}}}}}');
document.write('var timer_s_1 = timer_s_1*60;');
document.write('var timer_s_2 = timer_s_2*60;');
document.write('var timer_m_1 = timer_m_1*60;');
document.write('var timer_m_2 = timer_m_2*60;');
document.write('var timer_h_1 = timer_h_1*60;');
document.write('var timer_h_2 = timer_h_2*60;');
document.write('var timer_d_1 = timer_d_1*60;');
document.write('var timer_d_2 = timer_d_2*60;');
document.write('document.getElementById(\'cis_new_year_d_1\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_d_1 +\'px;"></div>\';');
document.write('document.getElementById(\'cis_new_year_d_2\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_d_2 +\'px;"></div>\';');
document.write('document.getElementById(\'cis_new_year_h_1\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_h_1 +\'px;"></div>\';');
document.write('document.getElementById(\'cis_new_year_h_2\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_h_2 +\'px;"></div>\';');
document.write('document.getElementById(\'cis_new_year_m_1\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_m_1 +\'px;"></div>\';');
document.write('document.getElementById(\'cis_new_year_m_2\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_m_2 +\'px;"></div>\';');
document.write('document.getElementById(\'cis_new_year_s_1\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_s_1 +\'px;"></div>\';');
document.write('document.getElementById(\'cis_new_year_s_2\').innerHTML = \'<div class="timer" style="background-position: 0 -\' + timer_s_2 +\'px;"></div>\';');
document.write('} else {');
document.write('var time=new Date();');
document.write('var time_year=time.getFullYear();');
document.write('var name_year=((time_year<1970)?"0":"")+time_year;');
document.write('var str=name_year;');
document.write('var time_year_1=str.slice(0, 1);');
document.write('var time_year_2=str.slice(1, 2);');
document.write('var time_year_3=str.slice(2, 3);');
document.write('var time_year_4=str.slice(3, 4);');
document.write('var time_month=time.getMonth()+1;');
document.write('var name_month=((time_month<10)?"0":"")+time_month;');
document.write('var str=name_month;');
document.write('var time_month_1=str.slice(0, 1);');
document.write('var time_month_2=str.slice(1, 2);');
document.write('var time_date=time.getDate();');
document.write('var name_date=((time_date<10)?"0":"")+time_date;');
document.write('var str=name_date;');
document.write('var time_date_1=str.slice(0, 1);');
document.write('var time_date_2=str.slice(1, 2);');
document.write('document.getElementById("cis_new_year_heppi_timer").className = \'cis_new_year_timers_stop\';');
document.write('document.getElementById("cis_new_year_heppi_timer_1").className = \'cis_new_year_timers_stop_1\';');
document.write('document.getElementById(\'cis_new_year_d_1\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_year_1 +\'.png)"></div>\';');
document.write('document.getElementById(\'cis_new_year_d_2\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_year_2 +\'.png)"></div>\';');
document.write('document.getElementById(\'cis_new_year_h_1\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_year_3 +\'.png)"></div>\';');
document.write('document.getElementById(\'cis_new_year_h_2\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_year_4 +\'.png)"></div>\';');
document.write('document.getElementById(\'cis_new_year_m_1\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_month_1 +\'.png)"></div>\';');
document.write('document.getElementById(\'cis_new_year_m_2\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_month_2 +\'.png)"></div>\';');
document.write('document.getElementById(\'cis_new_year_s_1\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_date_1 +\'.png)"></div>\';');
document.write('document.getElementById(\'cis_new_year_s_2\').innerHTML = \'<div class="timer" style="background-image: url(/templates/network/images/cis_new_year/\' + time_date_2 +\'.png)"></div>\';');
document.write('}');
document.write('return false;');
document.write('}');
document.write('</script>');
document.write('</div></td></tr></table><br />');
document.write('');